"""adicionar_linhas_referencia

Revision ID: 1b062914715c
Revises: a06cf71a0cf9
Create Date: 2026-06-05 13:45:13.699691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b062914715c'
down_revision: Union[str, None] = 'a06cf71a0cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('linha_points', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('predictions', sa.Column('linha_assists', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('predictions', sa.Column('linha_rebounds', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('predictions', sa.Column('linha_steals', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('predictions', sa.Column('linha_blocks', sa.Numeric(precision=6, scale=2), nullable=True))
    op.drop_constraint('uq_predictions_player_game', 'predictions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_predictions_player_game', 'predictions', ['player_id', 'game_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('predictions', 'linha_blocks')
    op.drop_column('predictions', 'linha_steals')
    op.drop_column('predictions', 'linha_rebounds')
    op.drop_column('predictions', 'linha_assists')
    op.drop_column('predictions', 'linha_points')
    # ### end Alembic commands ###
