"""adiciona_posicao_jogador

Revision ID: 3304096557aa
Revises: 1b062914715c
Create Date: 2026-06-16 22:34:02.961961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3304096557aa'
down_revision: Union[str, None] = '1b062914715c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('pos', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'pos')
    # ### end Alembic commands ###
