"""adicionar_resetar_senha

Revision ID: a06cf71a0cf9
Revises: d932c4b04b17
Create Date: 2026-04-04 13:19:16.848833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06cf71a0cf9'
down_revision: Union[str, None] = 'd932c4b04b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expira', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expira')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
