"""iniciando_schemas

Revision ID: e3b42f5ca86b
Revises: 
Create Date: 2025-11-23 22:58:51.646752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b42f5ca86b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.Text(), nullable=False),
    sa.Column('lastname', sa.Text(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_country', sa.Text(), nullable=True),
    sa.Column('nba_start', sa.Integer(), nullable=True),
    sa.Column('nba_pro', sa.Integer(), nullable=True),
    sa.Column('height_feet', sa.Integer(), nullable=True),
    sa.Column('height_inches', sa.Integer(), nullable=True),
    sa.Column('height_meters', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('weight_pounds', sa.Integer(), nullable=True),
    sa.Column('weight_kilograms', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('college', sa.Text(), nullable=True),
    sa.Column('affiliation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('season')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('nickname', sa.Text(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('all_star', sa.Boolean(), nullable=False),
    sa.Column('nba_franchise', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('date_end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('status_short', sa.Integer(), nullable=True),
    sa.Column('status_long', sa.Text(), nullable=True),
    sa.Column('periods_current', sa.Integer(), nullable=True),
    sa.Column('periods_total', sa.Integer(), nullable=True),
    sa.Column('periods_end_of_period', sa.Boolean(), nullable=True),
    sa.Column('arena_name', sa.Text(), nullable=True),
    sa.Column('arena_city', sa.Text(), nullable=True),
    sa.Column('arena_state', sa.Text(), nullable=True),
    sa.Column('arena_country', sa.Text(), nullable=True),
    sa.Column('times_tied', sa.Integer(), nullable=True),
    sa.Column('lead_changes', sa.Integer(), nullable=True),
    sa.Column('nugget', sa.Text(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('home_team_id <> away_team_id', name='chk_game_teams_different'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season'], ['seasons.season'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_team_season',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('league_code', sa.String(), nullable=False),
    sa.Column('jersey', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('pos', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season'], ['seasons.season'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'team_id', 'season', 'league_code', name='uq_player_team_season_league')
    )
    op.create_table('team_league_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('conference', sa.Text(), nullable=True),
    sa.Column('division', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'league_id', name='uq_team_league')
    )
    op.create_table('team_season_stats',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('fast_break_points', sa.Integer(), nullable=True),
    sa.Column('points_in_paint', sa.Integer(), nullable=True),
    sa.Column('biggest_lead', sa.Integer(), nullable=True),
    sa.Column('second_chance_points', sa.Integer(), nullable=True),
    sa.Column('points_off_turnovers', sa.Integer(), nullable=True),
    sa.Column('longest_run', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fgp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ftp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('tpp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('off_reb', sa.Integer(), nullable=True),
    sa.Column('def_reb', sa.Integer(), nullable=True),
    sa.Column('tot_reb', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('p_fouls', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season'], ['seasons.season'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'season')
    )
    op.create_table('game_team_scores',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('series_win', sa.Integer(), nullable=True),
    sa.Column('series_loss', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('linescore_q1', sa.Integer(), nullable=True),
    sa.Column('linescore_q2', sa.Integer(), nullable=True),
    sa.Column('linescore_q3', sa.Integer(), nullable=True),
    sa.Column('linescore_q4', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'team_id'),
    sa.UniqueConstraint('game_id', 'is_home', name='uq_game_side')
    )
    op.create_table('game_team_stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('fast_break_points', sa.Integer(), nullable=True),
    sa.Column('points_in_paint', sa.Integer(), nullable=True),
    sa.Column('biggest_lead', sa.Integer(), nullable=True),
    sa.Column('second_chance_points', sa.Integer(), nullable=True),
    sa.Column('points_off_turnovers', sa.Integer(), nullable=True),
    sa.Column('longest_run', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fgp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ftp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('tpp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('off_reb', sa.Integer(), nullable=True),
    sa.Column('def_reb', sa.Integer(), nullable=True),
    sa.Column('tot_reb', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('p_fouls', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'team_id')
    )
    op.create_table('player_game_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('pos', sa.String(), nullable=True),
    sa.Column('minutes', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fgp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ftp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('tpp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('off_reb', sa.Integer(), nullable=True),
    sa.Column('def_reb', sa.Integer(), nullable=True),
    sa.Column('tot_reb', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('p_fouls', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season'], ['seasons.season'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_game_stats')
    op.drop_table('game_team_stats')
    op.drop_table('game_team_scores')
    op.drop_table('team_season_stats')
    op.drop_table('team_league_info')
    op.drop_table('player_team_season')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('seasons')
    op.drop_table('players')
    op.drop_table('leagues')
    # ### end Alembic commands ###
