FROM apache/airflow:2.10.5-python3.11

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/airflow/modelos_ml /opt/airflow/relatorios_ml \
    && chown -R airflow:root /opt/airflow/modelos_ml /opt/airflow/relatorios_ml \
    && chmod -R 775 /opt/airflow/modelos_ml /opt/airflow/relatorios_ml

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
